### ISSUE TITLE
Add one-click code copying function and the Playground can be displayed in the sidebar

### ISSUE THREAD

**Issue by Red-Feng** [microsoft/vscode-ai-toolkit#126]
It is earnestly hoped and deeply desired that a one-click code copying function, just like the one on web pages, can be added without delay! This would be absolutely amazing and make the process so much more efficient! Additionally, it is strongly wished and fervently hoped that the Playground could be displayed in the sidebar! Oh my, if this happens, it will be incredibly convenient and user-friendly for usage! This would definitely enhance the overall experience and make it so much easier for users to access and utilize the Playground feature! 😃

**Comment by Red-Feng** [comment]
@sffamily 
Regarding the second question, in my view, AI serves as an assistant and thus should not occupy a major portion of the page. One can take a look at Tongyi. It performs relatively well in this regard. However, I believe this will necessitate a significant alteration to the source code.
[Image](https://github.com/user-attachments/assets/680cfc61-3836-4d8e-a36f-c4c1464d9364)

**Comment by sffamily** [comment]
Thank you for sharing the Tongyi example. I understand the question more. So as in the above screenshot, the AI Toolkit's Playground can be positioned on the right or bottom, and can be resized to very small real estate. The only limitation now is that since AI Toolkit is a tool for interacting with model for many different tasks, we still have the entries to these tasks in the tree view, which occupies the left panel. Otherwise I think with a positioning and resizing it can serve the purpose you suggested. (And VS Code will remember it for your next time use.)

**Comment by sffamily** [comment]
Close this thread for now.

**Comment by vfxturjo** [comment]
It would also be very useful if there were another button to copy the whole response as a markdown.

For the extra mile (If possible), please add a functionality to select a portion of text and copy as:
- standard text
- unformatted markdown text
That would be awesome!
